sudo: false

language: android
jdk: oraclejdk8

env:
  global:
    - ADB_INSTALL_TIMEOUT=10

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.0
    - android-25
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-17

branches:
  except:
    - gh-pages

before_install:
  - chmod +x gradlew

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-17 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - android list target
  - sh build.sh

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/